### ISSUE TITLE
All removals fail, no reason given.

### ISSUE THREAD

**Issue by charrowc** [noitcudni/bulk-slack-user-deactivation#2]
When I attempt to upload a csv file of email addresses to deactivate, they all fail. No error message is given, but the "failed" count is the count of users in my csv file, and the "successfully deactivated" count is 0. I also manually checked on several of the users, and none of them have been deactivated.

I have verified that the emails in the csv match the emails in slack, the csv format matches the example given, and I have the correct slack permissions to deactivate users. I can provide a screen recording if necessary. Please advise on how to proceed.

**Comment by noitcudni** [comment]
Just saw this. Someone else reported the same issue. They rebooted the computer and started working for them. I'm going to see if I can reproduce it. Btw, I'm guessing that you are an admin, correct?

**Comment by noitcudni** [comment]
![image](https://github.com/noitcudni/bulk-slack-user-deactivation/assets/78951/fe01c5a0-c6ff-493e-8304-4f15fc11726f)
Interesting, if I submit the same file enough times, I'd eventually reproduce the issue. Still looking.

**Comment by noitcudni** [comment]
In the meantime, can you try refreshing the page?

**Comment by noitcudni** [comment]
![image](https://github.com/noitcudni/bulk-slack-user-deactivation/assets/78951/187d8338-c806-491e-9864-7ed53d00080a)
Token is missing. This is for my own information.

**Comment by noitcudni** [comment]
I think I know how to reproduce it consistently. If you wait too long to submit the csv file, the background service worker times out. The auth token that has been previously cached when the page was loaded is now gone. That's why you are seeing failures. Once the page is refreshed, it should work again.

**Comment by charrowc** [comment]
Refreshing the page solved the issue, thank you!

**Comment by noitcudni** [comment]
Great!
